# Generated by Django 3.2.4 on 2021-06-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todolist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('purpose', models.CharField(choices=[('IN', 'Inquiry'), ('CO', 'Complaint'), ('FB', 'Feedback')], max_length=2)),
                ('message', models.TextField()),
            ],
        ),
    ]
