# Generated by Django 3.2.4 on 2021-06-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='role',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
